#!/usr/bin/env node
// Build engineering/ROUTER.md — a deterministic routing manifest so the model loads
// only the field/skill files a task needs, instead of reading everything to decide.
//
// No LLM, no network, no deps. Reads YAML-ish frontmatter (route_when) from field-pack
// files and name/description from skills, estimates tokens (chars/4), hashes content.
//
//   node scripts/build-router.mjs           # write ROUTER.md
//   node scripts/build-router.mjs --check    # exit 1 if ROUTER.md is stale (for hooks/CI)
//
// The router is a pure optimization: if ROUTER.md is missing or stale, MasterMind falls
// back to the prose pointers in active-field.md / field.md. It never becomes a dependency.

import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(ROOT, 'engineering', 'ROUTER.md')

const tokens = (s) => Math.round(s.length / 4)
const hash = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 8)

function frontmatter(body) {
  const m = body.match(/^---\n([\s\S]*?)\n---/)
  if (!m) return {}
  const fm = {}
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/)
    if (!kv) continue
    let [, k, v] = kv
    const arr = v.match(/^\[(.*)\]$/)
    fm[k] = arr ? arr[1].split(',').map((x) => x.trim()).filter(Boolean) : v.trim()
  }
  return fm
}

const walk = (dir) =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
        const p = path.join(dir, e.name)
        return e.isDirectory() ? walk(p) : p
      })
    : []

const nodes = []

// Field packs — routed by route_when frontmatter
for (const f of walk(path.join(ROOT, 'engineering', 'fields')).filter((p) => p.endsWith('.md'))) {
  const body = fs.readFileSync(f, 'utf8')
  const fm = frontmatter(body)
  if (!fm.route_when) continue // field.md (the pack TOC) and untagged files are skipped
  nodes.push({
    kind: 'field',
    field: fm.field || path.basename(path.dirname(f)),
    name: fm.name || path.basename(f, '.md'),
    tags: Array.isArray(fm.route_when) ? fm.route_when : [fm.route_when],
    tokens: tokens(body),
    hash: hash(body),
    path: path.relative(ROOT, f),
  })
}

// Skills — routed by their existing name + description
for (const f of walk(path.join(ROOT, 'skills')).filter((p) => p.endsWith('SKILL.md'))) {
  const body = fs.readFileSync(f, 'utf8')
  const fm = frontmatter(body)
  if (!fm.name) continue
  nodes.push({
    kind: 'skill',
    field: '—',
    name: fm.name,
    tags: [String(fm.description || '').replace(/\s+/g, ' ').slice(0, 120)],
    tokens: tokens(body),
    hash: hash(body),
    path: path.relative(ROOT, f),
  })
}

nodes.sort((a, b) => a.kind.localeCompare(b.kind) || a.field.localeCompare(b.field) || a.name.localeCompare(b.name))

const row = (n) => `| \`${n.name}\` | ${n.field} | ${n.tags.join(', ')} | ${n.tokens} | ${n.path} | ${n.hash} |`
const section = (kind, title) => {
  const rows = nodes.filter((n) => n.kind === kind)
  if (!rows.length) return ''
  return `## ${title}\n\n| node | field | route_when | tokens | path | hash |\n| --- | --- | --- | --- | --- | --- |\n${rows.map(row).join('\n')}\n`
}

const total = nodes.reduce((s, n) => s + n.tokens, 0)
const manifest = `# ROUTER — load only what the task needs

Generated by \`scripts/build-router.mjs\` — do not edit by hand. Match the task to a node's
\`route_when\`, then load **only** that node's \`path\`. Loading everything here would cost ~${total} tokens;
routing loads the manifest (~this file) plus the 1–2 matched files instead.

If this file is missing or stale (a \`hash\` no longer matches its file), ignore it and fall back to the
prose pointers in \`active-field.md\` / each field's \`field.md\`. The router only ever speeds things up.

${section('field', 'Field-pack files')}
${section('skill', 'Skills')}`

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
  if (current.trim() !== manifest.trim()) {
    console.error('✖ ROUTER.md is stale — run: node scripts/build-router.mjs')
    process.exit(1)
  }
  console.log('✓ ROUTER.md is up to date')
} else {
  fs.writeFileSync(OUT, manifest)
  console.log(`✓ wrote ROUTER.md — ${nodes.length} nodes, ${total} tokens catalogued`)
}
